env:
  browser: true
  node: true
  es6: true
  mocha: true
extends: 'airbnb'
parserOptions:
  sourceType: module
rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  max-len:
    - 1
    - 80